version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      -  aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 980921722018.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      -  npm install
      -  npm run build
      -  docker build -t 980921722018.dkr.ecr.ap-northeast-1.amazonaws.com/gsq-ecr:latest ./
      -  docker push 980921722018.dkr.ecr.ap-northeast-1.amazonaws.com/gsq-ecr:latest
  post_build:
    commands:
      -  echo Build completed on `date`
      -  printf '[{"name":"mynginx","imageUri":"%s"}]' 980921722018.dkr.ecr.ap-northeast-1.amazonaws.com/gsq-ecr:latest > imagedefinitions.json
      -  cat imagedefinitions.json
artifacts:
  files:
    -  imagedefinitions.json